[package]
name = "relaycode-core"
version = "1.0.0"
edition = "2021"

[dependencies]
relaycode-schema = { path = "../relaycode-schema" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["sync", "rt", "time"] }
rand = "0.8"
